/*
 * File: app/model/Sales.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GridSample2.model.Sales', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Integer'
    ],

    fields: [
        {
            type: 'string',
            name: 'branch'
        },
        {
            type: 'int',
            name: 'yx1'
        },
        {
            type: 'int',
            name: 'yx2'
        },
        {
            type: 'int',
            name: 'yx3'
        },
        {
            type: 'int',
            name: 'yx4'
        },
        {
            type: 'int',
            name: 'yx5'
        },
        {
            type: 'int',
            name: 'yx6'
        },
        {
            type: 'int',
            name: 'yx7'
        },
        {
            type: 'int',
            name: 'yx8'
        },
        {
            type: 'int',
            name: 'yx9'
        }
    ]
});